cloud:
  version: 7
  product: SUSE OpenStack Cloud

admin_node:
  os:
    name: SUSE Linux Enterprise Server 12
    version: 12-SP2

  ip: localhost
  ssh:
    user: root
    password: linux
    port: 22

  api:
    user: crowbar
    password: crowbar
    port: 80
    ssl: false

control_node:
  ssh:
    user: root
    password:
    port: 22

nodes:
  - name:
    ssh:
      user: root
      password: linux
      port: 22

timeout:
  ssh: 15
  http: 5

